version: "3.1"
services:
    www:
        image: apaxe
        container_name: apache
        restart: always
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
#        links:
#            - db
        network_mode: host
    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: pruebas
            MYSQL_USER: php
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        network_mode: host
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin 
        links: 
            - db:db
        restart: always
        ports:
            - 8000:80
        environment:
            MYSQL_USER: php
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234 
volumes:
    persistent:
